contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "DevOps Blog"
canonifyurls  = true

DefaultContentLanguage = "en"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true

[Params]
  dateFormat = "January 2, 2019"
  commit = false
  rss = false

[Author]
  name = "Nick Valldares"
